### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by sagiegurari** [comment]
this seems to be unneeded. its a js module that checks env vars and has nothing to do with the actual cpu arch.
i see you pushed lots of such PRs all over. feels very strange and spammy.

**Comment by sibiraj-s** [comment]
Thanks @sagiegurari . 

@dineshks1 . The changes looks fine. but I am not sure of the benefits this brings. I also have plans on switching to Github Actions.

> i see you pushed lots of such PRs all over. feels very strange and spammy.

Yeah. @dineshks1 You have created several such PR's and why is that?

**Comment by dineshks1** [comment]
This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. for more info @gerrith3

**Comment by sagiegurari** [comment]
i'll be very straightforward for a sec, its a really bad way to do thing. really bad way to test your platform.
if node js comes with some patch, do they update all node js open source projects to test their patch on?
if google chrome got a patch, do they run on every open source web project?

if you want to test something, pull relevant projects and run them.
or better yet, write a proper test suite for your code. do not use other projects irrelevant tests for that.

**Comment by gerrith3** [comment]
@sagiegurari I think you may be confused as to the purpose of these changes.  IBM is trying to consolidate more of our hardware and do testing *just like Intel* at top of development trees, catching regressions as soon as they are added, rather than using millions of dollars of hardware scattered at various distributions and end sites.  The goal is to reduce our overall testing footprint while at the same time testing better - upstream at the source.  For the same reason that you test on top of tree with Intel, the same benefit happens when testing with other architectures, e.g. arm, s390x, etc.  We have done some extensive testing as various open source packages are used by ISVs, customers, etc. and while it seems like java, node, etc. should all be arch independent, or more pointedly, work on other architectures, the reality is that they don't.  We see something like 20-25% of some 100,000 npms fail on Power, usually for reasons that can be corrected/worked through fairly easily, but it is impossible to tell a priori which ones actually do work, without have some up front testing.  Our team has done the testing and validation, and then works to ensure that there is no regression by testing at top of tree.

**Comment by sagiegurari** [comment]
> can be corrected/worked through fairly easily

by whom?
reason i'm asking is, if its by IBM, then you should update your test suite to cover such issues.
If its by node.js/java/other platform, then you should work with them on having a test suite on your arc (like rust have test suite per arc split by tiers).
if its by the open source project that doesn't care about the arch, then I feel ppc64 has issues and can't expect to change the entire open source world to work by non standard behaviour of your arch.

**Comment by gerrith3** [comment]
@sagiegurari are you suggesting that IBM has test suites for your open source projects?  We rely strictly on community test suites for acceptance.  We do work with the distro to provide hardware, and they do some additoinal testing.  And I'm not following on the "arc" - we are working to get 100% parity with Intel for open source software - so no end user ever has to worry about broken or missing apps when they shift architectures from Intel to Arm to Power to s390x, etc.  We don't do your development or testing, but we do work with the distros which aggregate projects for end user consumption.  This is merely a step in reducing our carbon footprint for testing, providing more modern hardware to more developers, and ensuring that end users have a solid experience around multiple/varying architectures.

**Pull request closed without merging**
